/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.16.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.LiveToon.api;

import com.LiveToon.model.Character;
import com.LiveToon.model.Error;
import org.springframework.lang.Nullable;
import java.util.UUID;
import com.LiveToon.model.WorldsGet200Response;
import com.LiveToon.model.WorldsWorldIdCharactersGet200Response;
import com.LiveToon.model.WorldsWorldIdCharactersPostRequest;
import com.LiveToon.model.WorldsWorldIdStartPost201Response;
import com.LiveToon.model.WorldsWorldIdStartPostRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-09-29T19:10:41.347886+09:00[Asia/Seoul]", comments = "Generator version: 7.16.0")
@Validated
@Tag(name = "World", description = "the World API")
public interface WorldsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    public static final String PATH_WORLDS_GET = "/worlds";
    /**
     * GET /worlds : �멸퀎愿� 由ъ뒪�� 蹂닿린
     * �ъ슜 媛��ν븳 紐⑤뱺 �멸퀎愿� 紐⑸줉�� 議고쉶�⑸땲��
     *
     * @param page �섏씠吏� 踰덊샇 (1遺��� �쒖옉) (optional, default to 1)
     * @param limit �섏씠吏��� ��ぉ �� (optional, default to 20)
     * @param theme �멸퀎愿� �뚮쭏 �꾪꽣 (optional)
     * @param search �멸퀎愿� �대쫫 寃��� (optional)
     * @return �멸퀎愿� 紐⑸줉 議고쉶 �깃났 (status code 200)
     *         or �섎せ�� �붿껌 (status code 400)
     */
    @Operation(
        operationId = "worldsGet",
        summary = "�멸퀎愿� 由ъ뒪�� 蹂닿린",
        description = "�ъ슜 媛��ν븳 紐⑤뱺 �멸퀎愿� 紐⑸줉�� 議고쉶�⑸땲��",
        tags = { "World" },
        responses = {
            @ApiResponse(responseCode = "200", description = "�멸퀎愿� 紐⑸줉 議고쉶 �깃났", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WorldsGet200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "�섎せ�� �붿껌", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WorldsApi.PATH_WORLDS_GET,
        produces = { "application/json" }
    )
    
    default ResponseEntity<WorldsGet200Response> worldsGet(
        @Min(1) @Parameter(name = "page", description = "�섏씠吏� 踰덊샇 (1遺��� �쒖옉)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Min(1) @Max(100) @Parameter(name = "limit", description = "�섏씠吏��� ��ぉ ��", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit,
        @Parameter(name = "theme", description = "�멸퀎愿� �뚮쭏 �꾪꽣", in = ParameterIn.QUERY) @Valid @RequestParam(value = "theme", required = false) @Nullable String theme,
        @Parameter(name = "search", description = "�멸퀎愿� �대쫫 寃���", in = ParameterIn.QUERY) @Valid @RequestParam(value = "search", required = false) @Nullable String search
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"worlds\" : [ { \"updated_at\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"description\" : \"description\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"theme\" : \"fantasy\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"thumbnail_url\" : \"https://openapi-generator.tech\" }, { \"updated_at\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"description\" : \"description\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"theme\" : \"fantasy\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"thumbnail_url\" : \"https://openapi-generator.tech\" } ], \"pagination\" : { \"total\" : 1, \"limit\" : 6, \"page\" : 0, \"total_pages\" : 5 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"{}\", \"error\" : \"error\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_WORLDS_WORLD_ID_CHARACTERS_GET = "/worlds/{world_id}/characters";
    /**
     * GET /worlds/{world_id}/characters : �대떦 �멸퀎愿� 二쇱씤怨� 由ъ뒪�� 蹂닿린
     * �뱀젙 �멸퀎愿��� 罹먮┃�� 紐⑸줉�� 議고쉶�⑸땲��
     *
     * @param worldId �멸퀎愿� ID (required)
     * @param page �섏씠吏� 踰덊샇 (optional, default to 1)
     * @param limit �섏씠吏��� ��ぉ �� (optional, default to 20)
     * @return 罹먮┃�� 紐⑸줉 議고쉶 �깃났 (status code 200)
     *         or �멸퀎愿��� 李얠쓣 �� �놁쓬 (status code 404)
     */
    @Operation(
        operationId = "worldsWorldIdCharactersGet",
        summary = "�대떦 �멸퀎愿� 二쇱씤怨� 由ъ뒪�� 蹂닿린",
        description = "�뱀젙 �멸퀎愿��� 罹먮┃�� 紐⑸줉�� 議고쉶�⑸땲��",
        tags = { "World" },
        responses = {
            @ApiResponse(responseCode = "200", description = "罹먮┃�� 紐⑸줉 議고쉶 �깃났", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WorldsWorldIdCharactersGet200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "�멸퀎愿��� 李얠쓣 �� �놁쓬", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = WorldsApi.PATH_WORLDS_WORLD_ID_CHARACTERS_GET,
        produces = { "application/json" }
    )
    
    default ResponseEntity<WorldsWorldIdCharactersGet200Response> worldsWorldIdCharactersGet(
        @NotNull @Parameter(name = "world_id", description = "�멸퀎愿� ID", required = true, in = ParameterIn.PATH) @PathVariable("world_id") UUID worldId,
        @Min(1) @Parameter(name = "page", description = "�섏씠吏� 踰덊샇", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Min(1) @Max(100) @Parameter(name = "limit", description = "�섏씠吏��� ��ぉ ��", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"characters\" : [ { \"world_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"appearance\" : \"appearance\", \"personality\" : \"personality\", \"avatar_url\" : \"https://openapi-generator.tech\", \"name\" : \"name\", \"description\" : \"description\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"world_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"appearance\" : \"appearance\", \"personality\" : \"personality\", \"avatar_url\" : \"https://openapi-generator.tech\", \"name\" : \"name\", \"description\" : \"description\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ], \"pagination\" : { \"total\" : 1, \"limit\" : 6, \"page\" : 0, \"total_pages\" : 5 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"{}\", \"error\" : \"error\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_WORLDS_WORLD_ID_CHARACTERS_POST = "/worlds/{world_id}/characters";
    /**
     * POST /worlds/{world_id}/characters : �대떦 �멸퀎愿� �뚮쭏濡� 二쇱씤怨� 留뚮뱾湲�
     * �뱀젙 �멸퀎愿��� �뚮쭏�� 留욌뒗 �덈줈�� 罹먮┃�곕� �앹꽦�⑸땲��
     *
     * @param worldId �멸퀎愿� ID (required)
     * @param worldsWorldIdCharactersPostRequest  (required)
     * @return 罹먮┃�� �앹꽦 �깃났 (status code 201)
     *         or �섎せ�� �붿껌 (status code 400)
     *         or �멸퀎愿��� 李얠쓣 �� �놁쓬 (status code 404)
     *         or 罹먮┃�� �대쫫 以묐났 (status code 409)
     */
    @Operation(
        operationId = "worldsWorldIdCharactersPost",
        summary = "�대떦 �멸퀎愿� �뚮쭏濡� 二쇱씤怨� 留뚮뱾湲�",
        description = "�뱀젙 �멸퀎愿��� �뚮쭏�� 留욌뒗 �덈줈�� 罹먮┃�곕� �앹꽦�⑸땲��",
        tags = { "World" },
        responses = {
            @ApiResponse(responseCode = "201", description = "罹먮┃�� �앹꽦 �깃났", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Character.class))
            }),
            @ApiResponse(responseCode = "400", description = "�섎せ�� �붿껌", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "�멸퀎愿��� 李얠쓣 �� �놁쓬", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "罹먮┃�� �대쫫 以묐났", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = WorldsApi.PATH_WORLDS_WORLD_ID_CHARACTERS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Character> worldsWorldIdCharactersPost(
        @NotNull @Parameter(name = "world_id", description = "�멸퀎愿� ID", required = true, in = ParameterIn.PATH) @PathVariable("world_id") UUID worldId,
        @Parameter(name = "WorldsWorldIdCharactersPostRequest", description = "", required = true) @Valid @RequestBody WorldsWorldIdCharactersPostRequest worldsWorldIdCharactersPostRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"world_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"appearance\" : \"appearance\", \"personality\" : \"personality\", \"avatar_url\" : \"https://openapi-generator.tech\", \"name\" : \"name\", \"description\" : \"description\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"{}\", \"error\" : \"error\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"{}\", \"error\" : \"error\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"{}\", \"error\" : \"error\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    public static final String PATH_WORLDS_WORLD_ID_START_POST = "/worlds/{world_id}/start";
    /**
     * POST /worlds/{world_id}/start : �멸퀎愿� �쒖옉 �ㅽ넗由� �쒓났
     * �뱀젙 �멸퀎愿��먯꽌 �덈줈�� �ㅽ넗由щ� �쒖옉�⑸땲��
     *
     * @param worldId �멸퀎愿� ID (required)
     * @param worldsWorldIdStartPostRequest  (required)
     * @return �ㅽ넗由� �쒖옉 �깃났 (status code 201)
     *         or �섎せ�� �붿껌 (status code 400)
     *         or �멸퀎愿� �먮뒗 罹먮┃�곕� 李얠쓣 �� �놁쓬 (status code 404)
     */
    @Operation(
        operationId = "worldsWorldIdStartPost",
        summary = "�멸퀎愿� �쒖옉 �ㅽ넗由� �쒓났",
        description = "�뱀젙 �멸퀎愿��먯꽌 �덈줈�� �ㅽ넗由щ� �쒖옉�⑸땲��",
        tags = { "Story" },
        responses = {
            @ApiResponse(responseCode = "201", description = "�ㅽ넗由� �쒖옉 �깃났", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WorldsWorldIdStartPost201Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "�섎せ�� �붿껌", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "�멸퀎愿� �먮뒗 罹먮┃�곕� 李얠쓣 �� �놁쓬", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = WorldsApi.PATH_WORLDS_WORLD_ID_START_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<WorldsWorldIdStartPost201Response> worldsWorldIdStartPost(
        @NotNull @Parameter(name = "world_id", description = "�멸퀎愿� ID", required = true, in = ParameterIn.PATH) @PathVariable("world_id") UUID worldId,
        @Parameter(name = "WorldsWorldIdStartPostRequest", description = "", required = true) @Valid @RequestBody WorldsWorldIdStartPostRequest worldsWorldIdStartPostRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"first_scene\" : { \"is_final\" : true, \"image_url\" : \"https://openapi-generator.tech\", \"story_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"title\" : \"title\", \"choices\" : [ { \"next_scene_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"consequence\" : \"consequence\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"text\" : \"text\" }, { \"next_scene_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"consequence\" : \"consequence\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"text\" : \"text\" } ], \"content\" : \"content\" }, \"story\" : { \"world_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"updated_at\" : \"2000-01-23T04:56:07.000+00:00\", \"description\" : \"description\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"title\" : \"title\", \"current_scene_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : \"active\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"{}\", \"error\" : \"error\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"{}\", \"error\" : \"error\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
